# Site settings
title: Humans &middot; FRC 4501
email: admin@firsthumans.org
description: "A FIRST Robotics Team located in Santa Monica, California. We build robots!"
baseurl: ""
url: "http://firsthumans.org"
twitter_username: humans4501
github_username:  frchumans4501

# Build settings
markdown: kramdown
permalink: pretty

#SASS
sass:
    sass_dir: _sass